version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/postgres
      YANDEX_CLIENT_ID: 9c268abc73d84feda46bc566ac9be6b5
      YANDEX_CLIENT_SECRET: 87d131e7aa1e429c95374ca83256b13b
      YANDEX_REDIRECT_URI: http://localhost:8000/auth/yandex/callback
      SECRET_KEY: your_secret_key
      UPLOAD_DIRECTORY: /app/uploads
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db

volumes:
  postgres_data:
